### ISSUE TITLE
Problem with JoinTables in Doctrine

### ISSUE THREAD

**Issue by nuncanada** [ncrypthic/doctrine-graphql#4]
Currently the code is complaining about missing 'joinColumn' index, problematic line:

$joinColumns = $owningSide->getAssociationMapping($fieldDef['mappedBy'])['joinColumns'];

There might not be joinColumns metadata, only joinTable ones.

For the time being, I have made an workaround, but will try to make a proper fix and send a PR.

**Comment by nuncanada** [comment]
That has been solved in the pull request #13

**Comment by ncrypthic** [comment]
Thanks @nuncanada 👍
