### ISSUE TITLE
Problems with blob fields

### ISSUE THREAD

**Issue by nuncanada** [ncrypthic/doctrine-graphql#5]
The line 
SchemaUtil::mapTypeToGraphqlType($fieldDef['type'], $fieldDef['nullable'], false)->value()

at the registerObjects function in DoctrineGraphQL.php

throws an Exception, because this Maybe type doesn't have a value in those cases.

**Comment by nuncanada** [comment]
I have a fix for that in my fork, I have sent it in this pull request:
https://github.com/ncrypthic/doctrine-graphql/pull/3

**Comment by ncrypthic** [comment]
Thank you
